mime-form-decode: mime::Parser Class Reference
mime::Parser Class Reference abstract
#include <Parser.h>
Public Member Functions
Parser ()
virtual ~Parser ()
virtual void parse (unsigned char c)=0
virtual void close ()
Detailed Description
Definition at line 10 of file Parser.h.
Constructor & Destructor Documentation
mime::Parser::Parser () inline
Definition at line 13 of file Parser.h.
virtual mime::Parser::~Parser () inline virtual
Definition at line 14 of file Parser.h.
Member Function Documentation
virtual void mime::Parser::close () inline virtual
Reimplemented in mime::MultipartParser, mime::QuotedPrintableParser, mime::Base64Parser, mime::AnyObjectParser, and mime::SimpleParser.
Definition at line 17 of file Parser.h.
Referenced by mime::AnyObjectParser::close(), mime::Decoder::close(), mime::MultipartParser::close(), and mime::MultipartParser::parse().
virtual void mime::Parser::parse (unsigned char c) pure virtual
Implemented in mime::HeaderParser, mime::MultipartParser, mime::QuotedPrintableParser, mime::Base64Parser, mime::AnyObjectParser, and mime::SimpleParser.
Referenced by mime::MultipartParser::close(), mime::Decoder::decode(), mime::AnyObjectParser::parse(), and mime::MultipartParser::parse().
The documentation for this class was generated from the following file:
Parser.h