mime-form-decode: mime::ObjectParser Class Reference
mime::ObjectParser Class Reference abstract
#include <ObjectParser.h>
Public Member Functions
ObjectParser (ClientInterface *client, Object *obj)
virtual void parse (unsigned char c)=0
virtual void close ()
Public Attributes
ClientInterface * client
Object * obj
Detailed Description
Definition at line 9 of file ObjectParser.h.
Constructor & Destructor Documentation
ObjectParser::ObjectParser (ClientInterface * client, Object * obj)
Definition at line 6 of file ObjectParser.cpp.
References client, and obj.
Member Function Documentation
virtual void mime::Parser::close () inline virtual inherited
Reimplemented in mime::MultipartParser, mime::QuotedPrintableParser, mime::Base64Parser, mime::AnyObjectParser, and mime::SimpleParser.
Definition at line 17 of file Parser.h.
Referenced by mime::AnyObjectParser::close(), mime::Decoder::close(), mime::MultipartParser::close(), and mime::MultipartParser::parse().
virtual void mime::Parser::parse (unsigned char c) pure virtual inherited
Implemented in mime::HeaderParser, mime::MultipartParser, mime::QuotedPrintableParser, mime::Base64Parser, mime::AnyObjectParser, and mime::SimpleParser.
Referenced by mime::MultipartParser::close(), mime::Decoder::decode(), mime::AnyObjectParser::parse(), and mime::MultipartParser::parse().
Member Data Documentation
ClientInterface* mime::ObjectParser::client
Definition at line 14 of file ObjectParser.h.
Referenced by mime::Base64Parser::close(), mime::QuotedPrintableParser::close(), ObjectParser(), mime::SimpleParser::parse(), mime::AnyObjectParser::parse(), mime::Base64Parser::parse(), mime::QuotedPrintableParser::parse(), and mime::MultipartParser::parse().
Object* mime::ObjectParser::obj
Definition at line 15 of file ObjectParser.h.
Referenced by mime::Base64Parser::close(), mime::QuotedPrintableParser::close(), ObjectParser(), mime::SimpleParser::parse(), mime::AnyObjectParser::parse(), mime::Base64Parser::parse(), mime::QuotedPrintableParser::parse(), and mime::MultipartParser::parse().
The documentation for this class was generated from the following files:
ObjectParser.h
ObjectParser.cpp