mime-form-decode: mime::ParserFactory Class Reference
mime::ParserFactory Class Reference
#include <ParserFactory.h>
Static Public Member Functions
static Parser * generic (ClientInterface *client, Object *obj)
static Parser * create (ClientInterface *client, Object *obj)
Detailed Description
Definition at line 14 of file ParserFactory.h.
Member Function Documentation
Parser * ParserFactory::create (ClientInterface * client, Object * obj) static
Definition at line 20 of file ParserFactory.cpp.
References mime::Object::fields, and mime::Object::type.
Referenced by mime::AnyObjectParser::parse().
Parser * ParserFactory::generic (ClientInterface * client, Object * obj) static
Definition at line 14 of file ParserFactory.cpp.
Referenced by mime::Decoder::decode(), and mime::MultipartParser::parse().
The documentation for this class was generated from the following files:
ParserFactory.h
ParserFactory.cpp