mime-form-decode: mime::StringDecoder Class Reference
mime::StringDecoder Class Reference
#include <StringDecoder.h>
Public Member Functions
StringDecoder ()
~StringDecoder ()
void processString (std::string input)
Public API method specifies MIME string to decode.
std::string getFormValue (std::string formName)
Public API method retrieves a MIME form data element value.
std::string dump ()
Public API method dumps all known MIME form data key-value pairs.
void close ()
The data producer should call this once all data has been presented to the decoder to finalise processing and clean up all resources.
void decode (unsigned char c)
The data produced should call this method to present data to the decoder.
Protected Member Functions
virtual void object_created (Object *object)
Implementation of class StringDecoder.
virtual void data_start (Object *obj)
Called when a MIME object's data starts to be read.
virtual void data (Object *obj, unsigned char *data, int len)
Called once per byte in the MIME object's data.
virtual void data_end (Object *obj)
Called when all the data from the MIME object has been delivered.
Protected Attributes
std::string part
std::map< std::string,
std::string > results
Detailed Description
Definition at line 18 of file StringDecoder.h.
Constructor & Destructor Documentation
mime::StringDecoder::StringDecoder () inline
Definition at line 21 of file StringDecoder.h.
mime::StringDecoder::~StringDecoder () inline
Definition at line 22 of file StringDecoder.h.
Member Function Documentation
void Decoder::close () inherited
The data producer should call this once all data has been presented to the decoder to finalise processing and clean up all resources.
Definition at line 28 of file Decoder.cpp.
References mime::Parser::close(), mime::Decoder::obj, and mime::Decoder::parser.
Referenced by main().
void StringDecoder::data (Object * object, unsigned char * data, int len) protected virtual
Called once per byte in the MIME object's data.
Saves that data to our class string for later use.
Parameters
data - pointer to actual data.
len - number of bytes in data passed.
object - an instance representing a MIME object.
Implements mime::ClientInterface.
Definition at line 43 of file StringDecoder.cpp.
References part.
void StringDecoder::data_end (Object * object) protected virtual
Called when all the data from the MIME object has been delivered.
Saves the string we built and the key name (e.g. form item name) to our hash (map) for future access.
Parameters
object - an instance representing a MIME object.
Implements mime::ClientInterface.
Definition at line 58 of file StringDecoder.cpp.
References mime::HeaderField::attributes, part, and results.
void StringDecoder::data_start (Object * object) protected virtual
Called when a MIME object's data starts to be read.
Parameters
object - an instance representing a MIME object.
Implements mime::ClientInterface.
Definition at line 29 of file StringDecoder.cpp.
References part.
void Decoder::decode (unsigned char c) inherited
The data produced should call this method to present data to the decoder.
Definition at line 15 of file Decoder.cpp.
References mime::ParserFactory::generic(), mime::Decoder::obj, mime::Parser::parse(), and mime::Decoder::parser.
Referenced by main(), and processString().
std::string StringDecoder::dump ()
Public API method dumps all known MIME form data key-value pairs.
Returns
string - one line per key-value pair.
Definition at line 99 of file StringDecoder.cpp.
References results.
Referenced by main().
std::string StringDecoder::getFormValue (std::string formName)
Public API method retrieves a MIME form data element value.
Parameters
string - the MIME form data element name to retrieve.
Returns
string - the form data.
Definition at line 85 of file StringDecoder.cpp.
References results.
Referenced by main().
void StringDecoder::object_created (Object * object) protected virtual
Implementation of class StringDecoder.
Decodes a MIME string and allows retrieving form data values given a key when MIME content type is multipart/form-data.
Author
Chris Johnson Called when a MIME object is discovered in the input stream. Data may or may not follow.
Parameters
object - an instance representing a MIME object.
Implements mime::ClientInterface.
Definition at line 20 of file StringDecoder.cpp.
void StringDecoder::processString (std::string input)
Public API method specifies MIME string to decode.
Parameters
string - the MIME string to decode.
Definition at line 72 of file StringDecoder.cpp.
References mime::Decoder::decode().
Referenced by main().
Member Data Documentation
std::string mime::StringDecoder::part protected
Definition at line 29 of file StringDecoder.h.
Referenced by data(), data_end(), and data_start().
std::map<std::string, std::string> mime::StringDecoder::results protected
Definition at line 31 of file StringDecoder.h.
Referenced by data_end(), dump(), and getFormValue().
The documentation for this class was generated from the following files:
StringDecoder.h
StringDecoder.cpp