mime-form-decode: mime::ClientInterface Class Reference
mime::ClientInterface Class Reference abstract
Interface describes the events called as a MIME string is parsed.
#include <ClientInterface.h>
Public Member Functions
virtual void object_created (Object *object)=0
A MIME object has been discovered in the input data.
virtual void data_start (Object *obj)=0
A MIME object's data starts processing.
virtual void data (Object *obj, unsigned char *data, int len)=0
Deliver data parsed from the MIME object.
virtual void data_end (Object *obj)=0
All data from the MIME object has been delivered.
Detailed Description
Interface describes the events called as a MIME string is parsed.
To make the MIME decoder to do something useful, implement all these methods.
Definition at line 17 of file ClientInterface.h.
Member Function Documentation
virtual void mime::ClientInterface::data (Object * obj, unsigned char * data, int len) pure virtual
Deliver data parsed from the MIME object.
Implemented in mime::StringDecoder, and TestDecoder.
Referenced by mime::SimpleParser::parse(), mime::Base64Parser::parse(), and mime::QuotedPrintableParser::parse().
virtual void mime::ClientInterface::data_end (Object * obj) pure virtual
All data from the MIME object has been delivered.
Implemented in mime::StringDecoder, and TestDecoder.
Referenced by mime::SimpleParser::close(), mime::Base64Parser::close(), and mime::QuotedPrintableParser::close().
virtual void mime::ClientInterface::data_start (Object * obj) pure virtual
A MIME object's data starts processing.
Implemented in mime::StringDecoder, and TestDecoder.
Referenced by mime::Base64Parser::Base64Parser(), mime::QuotedPrintableParser::QuotedPrintableParser(), and mime::SimpleParser::SimpleParser().
virtual void mime::ClientInterface::object_created (Object * object) pure virtual
A MIME object has been discovered in the input data.
Data may or may not follow.
Implemented in mime::StringDecoder, and TestDecoder.
Referenced by mime::AnyObjectParser::parse().
The documentation for this class was generated from the following file:
ClientInterface.h