mime-form-decode: mime::HeaderParser Class Reference
mime::HeaderParser Class Reference
Locates and extracts MIME headers, and stores their field keynames and values.
#include <HeaderParser.h>
Public Member Functions
HeaderParser (Object *obj)
Implmentation of class HeaderParser.
virtual void parse (unsigned char c)
virtual void close ()
Private Types
enum {
KEY, VAL, ATTRKEY, ATTRVAL,
PREKEY, PREVAL, POSTVAL, EOL,
QTVAL, CR
}
Private Member Functions
void add_header (const std::string &key, const std::string &value)
void parse_attrs (HeaderField &fld)
void split (std::string &input, std::string &left, std::string &right, unsigned char spl)
Private Attributes
mime::Object * obj
std::string key
std::string value
enum mime::HeaderParser:: { ... } state
std::map< std::string,
std::string > attributes
Detailed Description
Locates and extracts MIME headers, and stores their field keynames and values.
TODO Could this have less stuff?
Definition at line 12 of file HeaderParser.h.
Member Enumeration Documentation
anonymous enum private
Enumerator
KEY
VAL
ATTRKEY
ATTRVAL
PREKEY
PREVAL
POSTVAL
EOL
QTVAL
CR
Definition at line 33 of file HeaderParser.h.
Constructor & Destructor Documentation
HeaderParser::HeaderParser (Object * obj)
Implmentation of class HeaderParser.
Locates and extracts MIME headers, and stores their field keynames and values.
Definition at line 13 of file HeaderParser.cpp.
References obj, PREKEY, and state.
Member Function Documentation
void HeaderParser::add_header (const std::string & key, const std::string & value) private
Definition at line 90 of file HeaderParser.cpp.
References mime::Object::fields, key, mime::HeaderField::key, obj, parse_attrs(), value, and mime::HeaderField::value.
Referenced by parse().
virtual void mime::Parser::close () inline virtual inherited
Reimplemented in mime::MultipartParser, mime::QuotedPrintableParser, mime::Base64Parser, mime::AnyObjectParser, and mime::SimpleParser.
Definition at line 17 of file Parser.h.
Referenced by mime::AnyObjectParser::close(), mime::Decoder::close(), mime::MultipartParser::close(), and mime::MultipartParser::parse().
void HeaderParser::parse (unsigned char c) virtual
Implements mime::Parser.
Definition at line 109 of file HeaderParser.cpp.
References add_header(), ATTRKEY, ATTRVAL, CR, EOL, mime::Object::fields, key, KEY, obj, POSTVAL, PREKEY, PREVAL, QTVAL, state, mime::Object::subtype, mime::Object::type, VAL, and value.
void HeaderParser::parse_attrs (HeaderField & fld) private
Definition at line 41 of file HeaderParser.cpp.
References mime::HeaderField::attributes, mime::HeaderField::key, split(), and mime::HeaderField::value.
Referenced by add_header().
void HeaderParser::split (std::string & input, std::string & left, std::string & right, unsigned char spl) private
Parameters
string input – string to split.
string left – output left half of string after split.
string right – output right half of string after split.
char spl – split on this character, include in left half output.
Definition at line 26 of file HeaderParser.cpp.
Referenced by parse_attrs().
Member Data Documentation
std::map<std::string, std::string> mime::HeaderParser::attributes private
Definition at line 38 of file HeaderParser.h.
std::string mime::HeaderParser::key private
Definition at line 17 of file HeaderParser.h.
Referenced by add_header(), and parse().
mime::Object* mime::HeaderParser::obj private
Definition at line 15 of file HeaderParser.h.
Referenced by add_header(), HeaderParser(), and parse().
enum { ... } mime::HeaderParser::state
Referenced by HeaderParser(), and parse().
std::string mime::HeaderParser::value private
Definition at line 18 of file HeaderParser.h.
Referenced by add_header(), and parse().
The documentation for this class was generated from the following files:
HeaderParser.h
HeaderParser.cpp