mime-form-decode: TestDecoder Class Reference
TestDecoder Class Reference
Test driver for the low-level event-driven Decoder API class.
Public Member Functions
TestDecoder ()
~TestDecoder ()
virtual void object_created (mime::Object *object)
A MIME object has been discovered in the input data.
virtual void data_start (mime::Object *obj)
A MIME object's data starts processing.
virtual void data (mime::Object *obj, unsigned char *data, int len)
Deliver data parsed from the MIME object.
virtual void data_end (mime::Object *obj)
All data from the MIME object has been delivered.
void close ()
The data producer should call this once all data has been presented to the decoder to finalise processing and clean up all resources.
void decode (unsigned char c)
The data produced should call this method to present data to the decoder.
Detailed Description
Test driver for the low-level event-driven Decoder API class.
Reads stdin until EOF, calling API for each character read. Implements the Decoder event methods are where something useful would be done.
Definition at line 17 of file try1.cpp.
Constructor & Destructor Documentation
TestDecoder::TestDecoder () inline
Definition at line 20 of file try1.cpp.
TestDecoder::~TestDecoder () inline
Definition at line 21 of file try1.cpp.
Member Function Documentation
void Decoder::close () inherited
The data producer should call this once all data has been presented to the decoder to finalise processing and clean up all resources.
Definition at line 28 of file Decoder.cpp.
References mime::Parser::close(), mime::Decoder::obj, and mime::Decoder::parser.
Referenced by main().
void TestDecoder::data (mime::Object * obj, unsigned char * data, int len) virtual
Deliver data parsed from the MIME object.
Implements mime::ClientInterface.
Definition at line 49 of file try1.cpp.
void TestDecoder::data_end (mime::Object * obj) virtual
All data from the MIME object has been delivered.
Implements mime::ClientInterface.
Definition at line 56 of file try1.cpp.
void TestDecoder::data_start (mime::Object * obj) virtual
A MIME object's data starts processing.
Implements mime::ClientInterface.
Definition at line 44 of file try1.cpp.
void Decoder::decode (unsigned char c) inherited
The data produced should call this method to present data to the decoder.
Definition at line 15 of file Decoder.cpp.
References mime::ParserFactory::generic(), mime::Decoder::obj, mime::Parser::parse(), and mime::Decoder::parser.
Referenced by main(), and mime::StringDecoder::processString().
void TestDecoder::object_created (mime::Object * object) virtual
A MIME object has been discovered in the input data.
Data may or may not follow.
Implements mime::ClientInterface.
Definition at line 29 of file try1.cpp.
References mime::Object::fields.
The documentation for this class was generated from the following file:
try1.cpp