mime-form-decode: mime::Decoder Class Reference
mime::Decoder Class Reference abstract
A class which knows how to decode MIME.
#include <Decoder.h>
Public Member Functions
Decoder ()
Default constructor.
virtual ~Decoder ()
void close ()
The data producer should call this once all data has been presented to the decoder to finalise processing and clean up all resources.
void decode (unsigned char c)
The data produced should call this method to present data to the decoder.
virtual void object_created (Object *object)=0
A MIME object has been discovered in the input data.
virtual void data_start (Object *obj)=0
A MIME object's data starts processing.
virtual void data (Object *obj, unsigned char *data, int len)=0
Deliver data parsed from the MIME object.
virtual void data_end (Object *obj)=0
All data from the MIME object has been delivered.
Private Attributes
Parser * parser
Object * obj
Detailed Description
A class which knows how to decode MIME.
To do something useful, derive a class from it, and implement all the calls in the ClientInterface interface.
Definition at line 16 of file Decoder.h.
Constructor & Destructor Documentation
Decoder::Decoder ()
Default constructor.
Definition at line 9 of file Decoder.cpp.
References obj, and parser.
virtual mime::Decoder::~Decoder () inline virtual
Definition at line 23 of file Decoder.h.
Member Function Documentation
void Decoder::close ()
The data producer should call this once all data has been presented to the decoder to finalise processing and clean up all resources.
Definition at line 28 of file Decoder.cpp.
References mime::Parser::close(), obj, and parser.
Referenced by main().
virtual void mime::ClientInterface::data (Object * obj, unsigned char * data, int len) pure virtual inherited
Deliver data parsed from the MIME object.
Implemented in mime::StringDecoder, and TestDecoder.
Referenced by mime::SimpleParser::parse(), mime::Base64Parser::parse(), and mime::QuotedPrintableParser::parse().
virtual void mime::ClientInterface::data_end (Object * obj) pure virtual inherited
All data from the MIME object has been delivered.
Implemented in mime::StringDecoder, and TestDecoder.
Referenced by mime::SimpleParser::close(), mime::Base64Parser::close(), and mime::QuotedPrintableParser::close().
virtual void mime::ClientInterface::data_start (Object * obj) pure virtual inherited
A MIME object's data starts processing.
Implemented in mime::StringDecoder, and TestDecoder.
Referenced by mime::Base64Parser::Base64Parser(), mime::QuotedPrintableParser::QuotedPrintableParser(), and mime::SimpleParser::SimpleParser().
void Decoder::decode (unsigned char c)
The data produced should call this method to present data to the decoder.
Definition at line 15 of file Decoder.cpp.
References mime::ParserFactory::generic(), obj, mime::Parser::parse(), and parser.
Referenced by main(), and mime::StringDecoder::processString().
virtual void mime::ClientInterface::object_created (Object * object) pure virtual inherited
A MIME object has been discovered in the input data.
Data may or may not follow.
Implemented in mime::StringDecoder, and TestDecoder.
Referenced by mime::AnyObjectParser::parse().
Member Data Documentation
Object* mime::Decoder::obj private
Definition at line 20 of file Decoder.h.
Referenced by close(), decode(), and Decoder().
Parser* mime::Decoder::parser private
Definition at line 19 of file Decoder.h.
Referenced by close(), decode(), and Decoder().
The documentation for this class was generated from the following files:
Decoder.h
Decoder.cpp