mime-form-decode: try2.cpp File Reference
try2.cpp File Reference
#include <iostream>
#include "StringDecoder.h"
Functions
int main (int argc, char **argv)
Test driver for the StringDecoder API class.
Function Documentation
int main (int argc, char ** argv)
Test driver for the StringDecoder API class.
Reads stdin until EOF, passes resulting string to API.
Author
Chris Johnson
Definition at line 15 of file try2.cpp.
References mime::Decoder::close(), mime::StringDecoder::dump(), mime::StringDecoder::getFormValue(), and mime::StringDecoder::processString().